//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PART2_POE_PROG6212
{


    public partial class EditClaim
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtClaimID;
        protected global::System.Web.UI.WebControls.TextBox txtLecturerName;
        protected global::System.Web.UI.WebControls.TextBox txtLecturerEmail;
        protected global::System.Web.UI.WebControls.DropDownList ddlModule;
        protected global::System.Web.UI.WebControls.TextBox txtClaimDate;
        protected global::System.Web.UI.WebControls.TextBox txtHoursWorked;
        protected global::System.Web.UI.WebControls.TextBox txtHourlyRate;
        protected global::System.Web.UI.WebControls.TextBox txtTotalClaim;
        protected global::System.Web.UI.WebControls.TextBox txtClaimStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}
